const COOKIE_NAME = "user_jwt_token";
const LOCAL_STORAGE_USER_KEY = "user";
const JWT_SECRET_KEY = "JWT_SECRET";
const SERVER_URL = process.env.NEXT_PUBLIC_SERVER_URL;
export { COOKIE_NAME, LOCAL_STORAGE_USER_KEY, SERVER_URL, JWT_SECRET_KEY };
